# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'System Overlord'
tagline:          'Security, CTFs, Hacking'
description:      'A blog about security engineering, research, and general hacking.'
url:              https://systemoverlord.com
baseurl:          /

author:
  name:           'David Tomaschik'
  url:            https://systemoverlord.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Matir/blog
  url:            https://github.com/Matir/

# Gems
gems:
  - jekyll-paginate
