# Dependencies
markdown:         kramdown
kramdown:
  syntax_highlighter: rouge
  input:          "GFM"
  hard_wrap:      false
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
sass:
  sass_dir: _sass

# Permalinks
permalink:        ":year/:month/:day/:title.html"

# Setup
title:            'System Overlord'
tagline:          'Security, CTFs, Hacking'
description:      'A blog about security engineering, research, and general hacking.'
url:              https://systemoverlord.com
baseurl:          
excerpt_separator: "<!--more-->"
remote_theme:            pages-themes/hacker@v0.2.0

author:
  name:           'David Tomaschik'
  url:            https://systemoverlord.com
  email:          david@systemoverlord.com

paginate:         5

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
  - _conf
  - _scripts
  - .sass-cache

# Custom vars
github:
  repository_url: https://github.com/Matir/blog
  repo:           https://github.com/Matir/blog
  url:            https://github.com/Matir/

# Gems
plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-sitemap

# Front matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      rss:    true
      hidden: false
