# Dependencies
markdown:         kramdown
kramdown:
  syntax_highlighter: rouge
  input:          "GFM"
  hard_wrap:      false

# Permalinks
permalink:        ":year/:month/:day/:title.html"

# Setup
title:            'System Overlord'
tagline:          'Security, CTFs, Hacking'
description:      'A blog about security engineering, research, and general hacking.'
url:              https://systemoverlord.com
baseurl:          /

author:
  name:           'David Tomaschik'
  url:            https://systemoverlord.com

paginate:         5

exclude:
  - README.md
  - LICENSE.md

# Custom vars
github:
  repo:           https://github.com/Matir/blog
  url:            https://github.com/Matir/

# Gems
gems:
  - jekyll-paginate
