#!/bin/bash

# Exit on any error
set -e

SRV_DIR=/srv/blog

export GEM_HOME=$(ruby -e 'puts Gem.user_dir')
export GEM_PATH=$GEM_HOME
export PATH=$GEM_HOME/bin:$PATH

TMP_REPO=`mktemp -d`
git clone ${GIT_DIR} ${TMP_REPO}
bundle install --gemfile=${TMP_REPO}/Gemfile
GIT_REV=$(git -C ${TMP_REPO} --git-dir .git rev-parse --short --verify HEAD)
jekyll build -s ${TMP_REPO} -d ${SRV_DIR}/${GIT_REV}
echo "Compressing html/css/js files."
find ${SRV_DIR}/${GIT_REV} -type f -name '*.html' -o -name '*.js' -o -name '*.css' | while read file ; do
  gzip < ${file} > ${file}.gz
done
echo "Linking ${SRV_DIR}/current to ${SRV_DIR}/${GIT_REV}"
ln -snf ${SRV_DIR}/${GIT_REV} ${SRV_DIR}/current

# Cleanup
rm -rf ${TMP_REPO}
for i in $(ls ${SRV_DIR} | grep -v current | grep -v ${GIT_REV}) ; do
  rm -rf ${SRV_DIR}/${i}
done
